version: 0.0
os: linux
# 폴더경로는 원하는 곳에 하시면 됩니다. 꼭  /usr/share/nginx/html/안에 들어가지 않아도 됩니다.
files:
  - source: /
    destination: /app
    overwrite: yes
permissions:
  - object: /app
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
